Use vendorHash instead of vendorSha256
Tried to build using Nixpkgs 24.11, but got:

    error: buildGoModule: Expect vendorHash instead of vendorSha256

Swapping out that attribute name (and using an appropriate SRI hash) seems to
work.